### ISSUE TITLE
LND Properties do not appear

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/lnd-wrapper#31] opened 2021-12-03 21:24 UTC
![image](https://user-images.githubusercontent.com/39687477/144674708-7921b6b0-33b4-4893-8c4d-6726e8c73ae8.png)

Reported by: @kn0wmad

**Comment by kn0wmad** [comment] 2021-12-07 14:32
> Cannot repro on 9c1840b0e9e3bcb192e878d51ec51e5c54792536 with the latest LND.
> 
> @kn0wmad could you verify if this is resolved for you when running in the above state?

Builiding a new image today, will report back

**Comment by elvece** [comment] 2022-01-15 00:10
I have no reason to believe that this is still a bug. Properties render fine afaict. 

However, this should be tested on a fresh install of LND - reassigning to @Blu-J since he has capacity and will have a freshly migrated 0.3.0 box to test this on.

**Comment by Blu-J** [comment] 2022-01-15 01:27
So, there are no properties that are sent to the frontend for the lightning, interesting. I'm guessing this is wrong
![image](https://user-images.githubusercontent.com/2364004/149603649-e81e9ae2-36b2-4d44-a4b1-25c922b77f31.png)

**Comment by Blu-J** [comment] 2022-01-15 01:57
So, the issue is that there is no stats.yaml for this system
![image](https://user-images.githubusercontent.com/2364004/149604613-28af1183-3c44-4e67-b2a9-261bde0368de.png)

**Comment by elvece** [comment] 2022-01-17 17:02
The path this file would exist at is `/root/.lnd/start9/stats.yaml`

It would not exist until after the [configurator has completed running](https://github.com/Start9Labs/lnd-wrapper/blob/integration/0.13.3.1/docker_entrypoint.sh#L6).

**Comment by Blu-J** [comment] 2022-01-17 22:25
`"{\"error\":\"the RPC server is in the process of starting up, but not yet ready to accept calls\",\"code\":2,\"message\":\"the RPC`

**Comment by ProofOfKeags** [comment] 2022-01-17 22:45
This is somewhat normal. LND takes some time to start up. This should resolve itself within 10-30 seconds. If it persists longer than that, it suggests something else going on. It may take longer if you have db compaction turned on and it has been a really long time since you last compacted the db.

**Comment by elvece** [comment] 2022-01-17 22:52
The health checks should indicate that the service is starting up, but I am not sure there is anything we can currently do for properties besides change the messaging to say something like "...Please be advised that values might not display here while the service is still booting up."

**Comment by Blu-J** [comment] 2022-01-20 19:58
The minimum that we are doing is at least indicating that we are waiting for the service to get up,

**Closed** 2022-01-24 17:10 UTC
Labels: Bug, P1 - Blocks Release
